import type { Metadata } from "next";
import { Navbar } from "@/components/layout/navbar";
import { Footer } from "@/components/layout/footer";
import { Database, Layers, Cpu, Link as LinkIcon, Server, ShieldCheck, Zap, GlobeLock } from "lucide-react";
import { CTABlock } from "@/components/ui/cta-block";

export const metadata: Metadata = {
  title: "Architecture | StrataFlow",
  description: "Explore the StrataFlow 5-layer operational intelligence architecture. Designed for zero-latency execution and enterprise-grade security.",
};

const LAYERS = [
  {
    id: "01",
    label: "INPUT LAYER",
    title: "Data Ingestion",
    desc: "We build secure bridges to your existing data. Whether it's a legacy ERP, a modern CRM, scattered spreadsheets, or raw web data, the Input Layer continuously extracts and standardizes information in real-time.",
    icon: Database,
    tech: ["Webhooks", "PostgreSQL", "Kafka", "AWS Kinesis", "Fivetran"],
    color: "var(--color-text-secondary)",
  },
  {
    id: "02",
    label: "PROCESSING LAYER",
    title: "Normalization & Encryption",
    desc: "Raw data is useless. The Processing Layer cleanses, validates against strict schemas, drops duplicates, and encrypts payloads before they touch the intelligence core. Zero Trust architecture is enforced here.",
    icon: Layers,
    tech: ["dbt", "Python", "AWS KMS", "Redis"],
    color: "var(--color-muted)",
  },
  {
    id: "03",
    label: "AI CORE",
    title: "Intelligence & Reasoning",
    desc: "The brain of the system. We deploy localized LLMs or secure API bridges (OpenAI, Anthropic) to analyze the normalized data. This layer performs semantic search, intent classification, and multi-step reasoning to determine the necessary action.",
    icon: Cpu,
    tech: ["GPT-4o", "Claude 3.5 Sonnet", "Pinecone", "LangChain"],
    color: "var(--color-primary)",
    highlight: true,
  },
  {
    id: "04",
    label: "AUTOMATION LAYER",
    title: "Orchestration",
    desc: "Once an intent is generated by the AI Core, the Automation layer maps it to physical tasks. It constructs API payloads, handles rate limiting, and prepares the exact actions required to execute the workflow.",
    icon: LinkIcon,
    tech: ["Node.js", "AWS Step Functions", "Celery", "RabbitMQ"],
    color: "var(--color-muted)",
  },
  {
    id: "05",
    label: "OUTPUT LAYER",
    title: "Execution & Routing",
    desc: "The payload hits your ecosystem. An email is sent, a lead is updated in Salesforce, a Zendesk ticket is closed, or a Slack alert is triggered. The loop closes, and the system logs the outcome.",
    icon: Server,
    tech: ["Salesforce API", "HubSpot API", "SendGrid", "Slack API"],
    color: "var(--color-text-secondary)",
  },
];

export default function ArchitecturePage() {
  return (
    <>
      <Navbar />
      <main className="pt-32 pb-24">
        <div className="sf-container">

          {/* Header */}
          <div className="max-w-4xl mb-32">
            <div className="sf-pipeline-label mb-8">SYSTEM BLUEPRINT</div>
            <h1 className="mb-8 tracking-tight text-5xl md:text-6xl lg:text-7xl">
              The 5-Layer <br /><span className="text-muted">Intelligence Pipeline.</span>
            </h1>
            <p className="text-xl text-text-secondary leading-relaxed max-w-3xl">
              We do not sell pre-packaged SaaS. We build highly customized, vertically integrated infrastructure that plugs directly into your existing operations. Every layer is isolated, scalable, and fully observable.
            </p>
          </div>

          {/* Security Banner */}
          <div className="flex flex-col md:flex-row gap-6 mb-24">
            <div className="flex-1 p-6 sf-glass rounded-[var(--sf-radius-md)] flex items-start gap-4 border border-border/50">
              <ShieldCheck className="w-8 h-8 text-primary flex-shrink-0" />
              <div>
                <h3 className="text-base mb-1">SOC2 Type II Ready</h3>
                <p className="text-sm text-muted">All infrastructure is deployed with strict IAM roles and VPC isolation.</p>
              </div>
            </div>
            <div className="flex-1 p-6 sf-glass rounded-[var(--sf-radius-md)] flex items-start gap-4 border border-border/50">
              <GlobeLock className="w-8 h-8 text-foreground flex-shrink-0" />
              <div>
                <h3 className="text-base mb-1">End-to-End Encryption</h3>
                <p className="text-sm text-muted">AES-256 encryption at rest and TLS 1.3 in transit. Zero data leakage.</p>
              </div>
            </div>
            <div className="flex-1 p-6 sf-glass rounded-[var(--sf-radius-md)] flex items-start gap-4 border border-border/50">
              <Zap className="w-8 h-8 text-foreground flex-shrink-0" />
              <div>
                <h3 className="text-base mb-1">Sub-100ms Latency</h3>
                <p className="text-sm text-muted">Edge-deployed serverless functions ensure rapid execution.</p>
              </div>
            </div>
          </div>

          {/* Vertical Stack Diagram */}
          <div className="relative w-full max-w-7xl mx-auto">
            {/* Connecting background line */}
            <div className="absolute left-[39px] md:left-[49px] top-12 bottom-12 w-px bg-border/50 hidden md:block" />

            <div className="flex flex-col gap-8 md:gap-16">
              {LAYERS.map((layer) => {
                const Icon = layer.icon;
                return (
                  <div key={layer.id} className="relative z-10 flex flex-col md:flex-row gap-6 md:gap-12 group">

                    {/* Node / Icon */}
                    <div className="flex items-start gap-6 md:w-1/3">
                      <div className={`flex-shrink-0 w-20 h-20 md:w-24 md:h-24 rounded-[var(--sf-radius-lg)] border sf-glass flex items-center justify-center transition-all duration-500 ${layer.highlight ? "border-primary bg-primary/5 shadow-[var(--sf-shadow-glow)]" : "border-border/50 group-hover:border-primary/50"}`}>
                        <Icon className="w-8 h-8 md:w-10 md:h-10" style={{ color: layer.color }} />
                      </div>
                      <div className="pt-2 md:hidden">
                        <div className="text-3xl font-mono font-bold text-border/50">{layer.id}</div>
                      </div>
                    </div>

                    {/* Content */}
                    <div className={`flex-1 p-10 md:p-12 rounded-[var(--sf-radius-lg)] border sf-glass transition-all duration-500 ${layer.highlight ? "border-primary/50 bg-surface/80 shadow-xl" : "border-border/50 hover:bg-surface/50"}`}>
                      <div className="flex justify-between items-start mb-6">
                        <div>
                          <div className="text-xs font-mono tracking-widest uppercase mb-3" style={{ color: layer.color }}>{layer.label}</div>
                          <h2 className="text-3xl font-bold">{layer.title}</h2>
                        </div>
                        <div className="hidden md:block text-5xl font-mono font-bold text-border/30 group-hover:text-border/60 transition-colors">
                          {layer.id}
                        </div>
                      </div>
                      <p className="text-lg text-muted leading-relaxed mb-8 max-w-4xl">{layer.desc}</p>

                      <div className="border-t border-border/50 pt-8 mt-8">
                        <div className="text-xs font-mono tracking-widest text-muted uppercase mb-4">Core Technologies</div>
                        <div className="flex flex-wrap gap-3">
                          {layer.tech.map((t) => (
                            <span key={t} className="text-sm font-mono bg-background border border-border/50 px-4 py-2 rounded-md text-foreground group-hover:border-primary/20 transition-colors">
                              {t}
                            </span>
                          ))}
                        </div>
                      </div>
                    </div>

                  </div>
                );
              })}
            </div>
          </div>

        </div>
      </main>

      <CTABlock
        title="Ready to deploy your architecture?"
        subtitle="Book a technical strategy session to review your existing stack and map out a custom operational intelligence pipeline."
      />
      <Footer />
    </>
  );
}
